apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: hysealab
  labels:
    app: git-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        args:
            - --repo=$REPO_URL
            - --ref=main
            - --period=60s
            - --link=toolbox
            - --root=/git
        volumeMounts:
        - name: toolbox-pv
          mountPath: /git

      volumes:
      - name: toolbox-pv
        persistentVolumeClaim:
          claimName: toolbox-pvc
