apiVersion: v1
kind: PersistentVolume
metadata:
  name: hysea-lab-$VOL_ID-pv
  namespace: hysealab
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/$EMAIL"
